namespace Zelda.Blocks
{
    public enum BlockType
    {
        Water,
        Sand,
        FishStatue,
        DragonStatue,
        ImmovableBlock,
        PushableBlock,
        Block2_1,
        InvisibleBlock,
        DoorUp,
        DoorDown,
        DoorRight,
        DoorLeft,
        DoorLockedUp,
        DoorLockedLeft,
        DoorLockedDown,
        DoorLockedRight,
        DoorSpecialLeft2_1,
        DoorSpecialRight3_1,
        StairSpecialUp1_1,
        BombableWallLeft,
        BombableWallRight,
        BombableWallTop,
        BombableWallBottom,
        DungeonStair,
        BasementStair,
        Fire,
        BlackBarrier
    }
}
